
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/util/cmake-3.27.0-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (enable_language)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/util/cmake-3.27.0-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/util/cmake-3.27.0-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/util/cmake-3.27.0-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (enable_language)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      .NET Framework용 Microsoft (R) Build Engine 버전 16.11.2+f32259642
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      빌드 시작: 2024-05-24 오전 9:00:09
      1 노드의 "D:\\testcode\\utill_testcode\\2405.1\\crulechk\\build219\\CMakeFiles\\3.27.0\\CompilerIdC\\CompilerIdC.vcxproj" 프로젝트(기본 대상)입니다.
      PrepareForBuild:
        "Debug\\" 디렉터리를 만들고 있습니다.
        "Debug\\CompilerIdC.tlog\\" 디렉터리를 만들고 있습니다.
      InitializeBuildStatus:
        "AlwaysCreate"이(가) 지정되었기 때문에 "Debug\\CompilerIdC.tlog\\unsuccessfulbuild"을(를) 만들고 있습니다.
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc142.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> D:\\testcode\\utill_testcode\\2405.1\\crulechk\\build219\\CMakeFiles\\3.27.0\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" 파일을 삭제하고 있습니다.
        "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate"에 연결(touching)하고 있습니다.
      "D:\\testcode\\utill_testcode\\2405.1\\crulechk\\build219\\CMakeFiles\\3.27.0\\CompilerIdC\\CompilerIdC.vcxproj" 프로젝트를 빌드했습니다(기본 대상).
      
      빌드했습니다.
          경고 0개
          오류 0개
      
      경과 시간: 00:00:00.74
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        D:/testcode/utill_testcode/2405.1/crulechk/build219/CMakeFiles/3.27.0/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/util/cmake-3.27.0-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/util/cmake-3.27.0-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/util/cmake-3.27.0-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (enable_language)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      .NET Framework용 Microsoft (R) Build Engine 버전 16.11.2+f32259642
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      빌드 시작: 2024-05-24 오전 9:00:10
      1 노드의 "D:\\testcode\\utill_testcode\\2405.1\\crulechk\\build219\\CMakeFiles\\3.27.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj" 프로젝트(기본 대상)입니다.
      PrepareForBuild:
        "Debug\\" 디렉터리를 만들고 있습니다.
        "Debug\\CompilerIdCXX.tlog\\" 디렉터리를 만들고 있습니다.
      InitializeBuildStatus:
        "AlwaysCreate"이(가) 지정되었기 때문에 "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild"을(를) 만들고 있습니다.
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc142.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> D:\\testcode\\utill_testcode\\2405.1\\crulechk\\build219\\CMakeFiles\\3.27.0\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" 파일을 삭제하고 있습니다.
        "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate"에 연결(touching)하고 있습니다.
      "D:\\testcode\\utill_testcode\\2405.1\\crulechk\\build219\\CMakeFiles\\3.27.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj" 프로젝트를 빌드했습니다(기본 대상).
      
      빌드했습니다.
          경고 0개
          오류 0개
      
      경과 시간: 00:00:00.53
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        D:/testcode/utill_testcode/2405.1/crulechk/build219/CMakeFiles/3.27.0/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/util/cmake-3.27.0-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/util/cmake-3.27.0-windows-x86_64/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (enable_language)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/testcode/utill_testcode/2405.1/crulechk/build219/CMakeFiles/CMakeScratch/TryCompile-q949f3"
      binary: "D:/testcode/utill_testcode/2405.1/crulechk/build219/CMakeFiles/CMakeScratch/TryCompile-q949f3"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/testcode/utill_testcode/2405.1/crulechk/build219/CMakeFiles/CMakeScratch/TryCompile-q949f3'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/MSBuild.exe" cmTC_dd5a1.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:n
        .NET Framework용 Microsoft (R) Build Engine 버전 16.11.2+f32259642
        Copyright (C) Microsoft Corporation. All rights reserved.
        
        빌드 시작: 2024-05-24 오전 9:00:11
        1 노드의 "D:\\testcode\\utill_testcode\\2405.1\\crulechk\\build219\\CMakeFiles\\CMakeScratch\\TryCompile-q949f3\\cmTC_dd5a1.vcxproj" 프로젝트(기본 대상)입니다.
        PrepareForBuild:
          "cmTC_dd5a1.dir\\Debug\\" 디렉터리를 만들고 있습니다.
          "D:\\testcode\\utill_testcode\\2405.1\\crulechk\\build219\\CMakeFiles\\CMakeScratch\\TryCompile-q949f3\\Debug\\" 디렉터리를 만들고 있습니다.
          "cmTC_dd5a1.dir\\Debug\\cmTC_dd5a1.tlog\\" 디렉터리를 만들고 있습니다.
        InitializeBuildStatus:
          "AlwaysCreate"이(가) 지정되었기 때문에 "cmTC_dd5a1.dir\\Debug\\cmTC_dd5a1.tlog\\unsuccessfulbuild"을(를) 만들고 있습니다.
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_dd5a1.dir\\Debug\\\\" /Fd"cmTC_dd5a1.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\util\\cmake-3.27.0-windows-x86_64\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ 최적화 컴파일러 버전 19.29.30151(x64)
          Copyright (c) Microsoft Corporation. All rights reserved.
          CMakeCCompilerABI.c
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_dd5a1.dir\\Debug\\\\" /Fd"cmTC_dd5a1.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\util\\cmake-3.27.0-windows-x86_64\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\testcode\\utill_testcode\\2405.1\\crulechk\\build219\\CMakeFiles\\CMakeScratch\\TryCompile-q949f3\\Debug\\cmTC_dd5a1.exe" /INCREMENTAL /ILK:"cmTC_dd5a1.dir\\Debug\\cmTC_dd5a1.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/testcode/utill_testcode/2405.1/crulechk/build219/CMakeFiles/CMakeScratch/TryCompile-q949f3/Debug/cmTC_dd5a1.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/testcode/utill_testcode/2405.1/crulechk/build219/CMakeFiles/CMakeScratch/TryCompile-q949f3/Debug/cmTC_dd5a1.lib" /MACHINE:X64  /machine:x64 cmTC_dd5a1.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_dd5a1.vcxproj -> D:\\testcode\\utill_testcode\\2405.1\\crulechk\\build219\\CMakeFiles\\CMakeScratch\\TryCompile-q949f3\\Debug\\cmTC_dd5a1.exe
        FinalizeBuildStatus:
          "cmTC_dd5a1.dir\\Debug\\cmTC_dd5a1.tlog\\unsuccessfulbuild" 파일을 삭제하고 있습니다.
          "cmTC_dd5a1.dir\\Debug\\cmTC_dd5a1.tlog\\cmTC_dd5a1.lastbuildstate"에 연결(touching)하고 있습니다.
        "D:\\testcode\\utill_testcode\\2405.1\\crulechk\\build219\\CMakeFiles\\CMakeScratch\\TryCompile-q949f3\\cmTC_dd5a1.vcxproj" 프로젝트를 빌드했습니다(기본 대상).
        
        빌드했습니다.
            경고 0개
            오류 0개
        
        경과 시간: 00:00:00.48
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/util/cmake-3.27.0-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/util/cmake-3.27.0-windows-x86_64/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (enable_language)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/testcode/utill_testcode/2405.1/crulechk/build219/CMakeFiles/CMakeScratch/TryCompile-sb744e"
      binary: "D:/testcode/utill_testcode/2405.1/crulechk/build219/CMakeFiles/CMakeScratch/TryCompile-sb744e"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/testcode/utill_testcode/2405.1/crulechk/build219/CMakeFiles/CMakeScratch/TryCompile-sb744e'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/MSBuild.exe" cmTC_3dcd0.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:n
        .NET Framework용 Microsoft (R) Build Engine 버전 16.11.2+f32259642
        Copyright (C) Microsoft Corporation. All rights reserved.
        
        빌드 시작: 2024-05-24 오전 9:00:12
        1 노드의 "D:\\testcode\\utill_testcode\\2405.1\\crulechk\\build219\\CMakeFiles\\CMakeScratch\\TryCompile-sb744e\\cmTC_3dcd0.vcxproj" 프로젝트(기본 대상)입니다.
        PrepareForBuild:
          "cmTC_3dcd0.dir\\Debug\\" 디렉터리를 만들고 있습니다.
          "D:\\testcode\\utill_testcode\\2405.1\\crulechk\\build219\\CMakeFiles\\CMakeScratch\\TryCompile-sb744e\\Debug\\" 디렉터리를 만들고 있습니다.
          "cmTC_3dcd0.dir\\Debug\\cmTC_3dcd0.tlog\\" 디렉터리를 만들고 있습니다.
        InitializeBuildStatus:
          "AlwaysCreate"이(가) 지정되었기 때문에 "cmTC_3dcd0.dir\\Debug\\cmTC_3dcd0.tlog\\unsuccessfulbuild"을(를) 만들고 있습니다.
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_3dcd0.dir\\Debug\\\\" /Fd"cmTC_3dcd0.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\util\\cmake-3.27.0-windows-x86_64\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ 최적화 컴파일러 버전 19.29.30151(x64)
          Copyright (c) Microsoft Corporation. All rights reserved.
          CMakeCXXCompilerABI.cpp
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_3dcd0.dir\\Debug\\\\" /Fd"cmTC_3dcd0.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\util\\cmake-3.27.0-windows-x86_64\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\testcode\\utill_testcode\\2405.1\\crulechk\\build219\\CMakeFiles\\CMakeScratch\\TryCompile-sb744e\\Debug\\cmTC_3dcd0.exe" /INCREMENTAL /ILK:"cmTC_3dcd0.dir\\Debug\\cmTC_3dcd0.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/testcode/utill_testcode/2405.1/crulechk/build219/CMakeFiles/CMakeScratch/TryCompile-sb744e/Debug/cmTC_3dcd0.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/testcode/utill_testcode/2405.1/crulechk/build219/CMakeFiles/CMakeScratch/TryCompile-sb744e/Debug/cmTC_3dcd0.lib" /MACHINE:X64  /machine:x64 cmTC_3dcd0.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_3dcd0.vcxproj -> D:\\testcode\\utill_testcode\\2405.1\\crulechk\\build219\\CMakeFiles\\CMakeScratch\\TryCompile-sb744e\\Debug\\cmTC_3dcd0.exe
        FinalizeBuildStatus:
          "cmTC_3dcd0.dir\\Debug\\cmTC_3dcd0.tlog\\unsuccessfulbuild" 파일을 삭제하고 있습니다.
          "cmTC_3dcd0.dir\\Debug\\cmTC_3dcd0.tlog\\cmTC_3dcd0.lastbuildstate"에 연결(touching)하고 있습니다.
        "D:\\testcode\\utill_testcode\\2405.1\\crulechk\\build219\\CMakeFiles\\CMakeScratch\\TryCompile-sb744e\\cmTC_3dcd0.vcxproj" 프로젝트를 빌드했습니다(기본 대상).
        
        빌드했습니다.
            경고 0개
            오류 0개
        
        경과 시간: 00:00:00.49
        
      exitCode: 0
...
