[package]
name = "D_1"
version = "0.1.0"
edition = "2021"

[profile.dev]
overflow-checks = false # @violation
debug-assertions = false # @violation

[profile.test]
overflow-checks = false  # @violation
debug-assertions = false # @violation

[dependencies]