[package]
name = "S_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
overflow-checks = true
debug-assertions = true

[profile.test]
overflow-checks = true
debug-assertions = true

[dependencies]