	//@checker DO_NOT_USE_UNUSED_MACRO_GLOBAL
	#define DATA 3; //@violation DO_NOT_USE_UNUSED_MACRO_GLOBAL
	#define SIZE 4;
	#define ALLO 5; //@violation DO_NOT_USE_UNUSED_MACRO_GLOBAL
	#define NONVALUE; //@violation DO_NOT_USE_UNUSED_MACRO_GLOBAL
